---
# file: group_vars/dhcpd.yml
dhcpd_domain_name: "lab.bewley.net"
dhcpd_domain_name_servers:
  - 192.168.1.177
dhcpd_next_server: 192.168.1.177
dhcpd_ddns_update_style: interim

dhcpd_subnets:
  - name: lab4
    description: Lab Network lab.bewley.net
    network: 192.168.4.0
    netmask: 255.255.255.0
    range_start: 192.168.4.10
    range_end: 192.168.4.199
    routers: 192.168.4.1
    next_server: 192.168.4.2
    domain_name_servers:
      - 192.168.4.2
    zone_key: lab.bewley.net
    zones:
      - domain: lab.bewley.net
        domain_name_server: 192.168.1.177
      - domain: 4.168.192.in-addr.arpa
        domain_name_server: 192.168.1.177

