---
- hosts: infra
  become: true
  become_user: root
  vars:
    #rhn_vars: /Volumes/Keybase/private/dlbewley/credz/redhat/vars.yml
    rhn_vars: /keybase/private/dlbewley/credz/redhat/vars.yml
    named_role: master
    packages:
      - bind-chroot
      - git
      - nfs-utils
      - squid
    firewall_services: []
      # - websm # cockpit
      # - http
      # - https
      # - mdns


    # disable this slow step for now.
    # enable if /usr/share/syslniux changes
    pxe_copy_syslinux: false
    pxe_repo_http_server: 192.168.4.2

  pre_tasks:
# [root@infra chroot]# firewall-cmd --new-zone wlan --permanent
# success
# [root@infra chroot]# firewall-cmd --zone wlan --add-source 192.168.3.0/24 --permanent
# success
# nmcli con modify disco ipv4.never-default yes
# nmcli con modify disco ipv6.never-default yes
# sysctl net.ipv4.ip_forward 1
    # $ nmcli con add type ethernet ifname ens224 con-name lab4 ipv4.addresses 192.168.4.2/24 ipv4.gateway 192.168.4.1 ipv4.method static
    # $ nmcli con add type ethernet ifname ens193 con-name lab5 ipv4.addresses 192.168.5.2/24 ipv4.gateway 192.168.5.1 ipv4.method static
    # $ nmcli con add type ethernet ifname ens193 con-name lab5 ipv4.addresses 192.168.5.2/24 ipv4.gateway 192.168.5.1 ipv4.method static
    # $ nmcli con add type ethernet ifname ens193 con-name lab5 ipv4.addresses 192.168.5.2/24 ipv4.gateway 192.168.5.1 ipv4.method static
    # $ nmcli con add type ethernet ifname ens225 con-name lab7 ipv4.addresses 192.168.7.2/24 ipv4.gateway 192.168.7.1 ipv4.method static
    # $ nmcli con up lab7
    # - name: Include Network Setup
    #   include_tasks: tasks/network-nmcli.yml
    - name: Include Red Hat pre tasks
      include_tasks: tasks/RedHat-pre-tasks.yml
      when: ansible_os_family == 'RedHat'
      tags: [ registration ]

  roles:
     - role: RedHatInsights.insights-client
       when: ansible_os_family == 'RedHat'
       tags: [ registration ]

     - role: mrlesmithjr.squid
       when: '"proxy" in group_names'
       tags: [ proxy ]

     - role: dhcpd
       when: '"dhcpd" in group_names'
       tags: [ dhcpd ]

     - role: pxe
       when: '"pxe" in group_names'
       tags: [ pxe ]

    #  - role: named
    #    when: '"named" in group_names'
    #    tags: [ named ]

  tasks:
      - name: install packages
        yum:
          name: "{{ packages }}"
          state: present

      - name: setup proxy server
        import_tasks: tasks/proxy-server.yml
        when: '"proxy" in group_names'
        tags: [ proxy ]

# TODO
# firewall-cmd --new-zone lab --permanent
# firewall-cmd --zone lab --add-source 192.168.4.0/24 --permanent
# firewall-cmd --zone lab --add-source 192.168.7.0/24 --permanent
# firewall-cmd --new-zone lab5 --permanent
# firewall-cmd --zone lab5 --add-source 192.168.5.0/24 --permanent
# firewall-cmd --new-zone disco --permanent
# firewall-cmd --zone disco --add-source 192.168.6.0/24 --permanen
# sysctl net.ipv4.ip_forward = 1
# sudo firewall-cmd –permanent –add-masquerade?

      - name: open firewall
        firewalld:
          service: "{{ item }}"
          state: enabled
          permanent: yes
        loop: 
          - "{{ firewall_services }}"
        when: firewall_services != []
        tags:
          - proxy
          - pxe
