---
# file: pxe/tasks/main.yml

- name: Install Packages
  yum:
    name: "{{ pxe_packages }}"
    state: installed

- name: Setup tftpboot directories
  file:
    path: "{{ pxe_tftpboot }}/{{ item }}"
    state: directory
    mode: 0755
    recurse: true
  loop:
    - boot/grub2
    - images/centos
    - images/fedora
    - images/ocp/4
    - images/rhcos
    - images/rhel/7
    - images/rhel/8
    - pxelinux/pxelinux.cfg
    - uefi

- name: Enumerate syslinux files
  find:
    path: "/usr/share/syslinux"
  register: syslinux_files

- name: Copy syslinux files to tftpboot
  copy:
    src: "{{ item.path }}"
    dest: "{{ pxe_tftpboot }}/"
    mode: 0644
    remote_src: true
  loop: "{{ syslinux_files.files }}"

- name: Copy UEFI images to tftpboot
  copy:
    src: "/boot/efi/EFI/redhat/{{ item }}"
    dest: "{{ pxe_tftpboot }}/uefi/{{ item }}"
    mode: 0644
    remote_src: true
  loop:
    - shimx64.efi
    - grubx64.efi

#- name: Install default pxe config
#  template:
#    src: default-menu.j2
#    dest: "{{ pxe_tftpboot }}/pxelinux/pxelinux.cfg/default"
#    mode: 0644

- name: Enable Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ pxe_services }}"

- name: Open Firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ pxe_firewall_services }}"
