---
# file: dhcpd/tasks/main.yml

- name: Install Packages
  yum:
    name: "{{ dhcpd_packages }}"
    state: installed

- name: Configure Service
  template:
    src: dhcpd.conf.j2
    dest: "{{ dhcpd_config }}"
    backup: yes
  notify: restart dhcpd

- name: Enable Services
  service:
    name: dhcpd
    enabled: yes
    state: started

- name: Open Firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
  loop: "{{ dhcpd_firewall_services }}"
