---
# tasks/RedHat-pre-tasks.yml

    - name: Include RedHat credential and connectivity vars
      include_vars: "{{ rhn_vars }}"
      no_log: True
      when: ansible_os_family == 'RedHat' and rhn_vars is defined

    - name: Register Red Hat Subscription
      redhat_subscription:
        state: present
        org_id: "{{ rhn_org_id }}"
        activationkey: "{{ rhn_activation_key }}"
        pool_ids: "{{ rhn_pool_ids }}"
      when: rhn_org_id is defined and ansible_os_family == 'RedHat'
