---
# ocp3/tasks/bastion.yml

- name: setup repos etc
  include_tasks: prep.yml

- name: install packages
  yum:
    name: "{{ ocp3_packages_bastion }}"
    state: installed

- name: checkout homelab repo
  git:
    repo: "{{ homelab_repo }}"
    dest: "/root/homelab"

- name: copy pull secret
  copy:
    content: "{{ pull_secret }}"
    dest: "{{ pull_secret_dest }}"
    owner: root
    mode: 0600

- name: copy rhn credential vars
  copy:
    src: "{{ rhn_vars }}"
    dest: /root/vars.yml
    owner: root
    mode: 0600

- name: drop a starting point inventory file
  template:
    src: hosts.{{ ocp_env }}.j2
    dest: /root/hosts

- name: TODO
  debug:
    msg: Update oreg_auth_password and oreg_auth_user in /root/hosts with pull secret

- name: TODO
  debug:
    msg: Generate bastion ssh key, add to authorized_keys on nodes

